name: Backend Tests for Updates to the Stack and to Build and Deploy to AWS

on:
  push:
    branches:
    - backend-crc

jobs:
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r Cloud-Resume-Challenge/backend/tests/requirements.txt

      - name: Set AWS_SAM_STACK_NAME
        run: echo "AWS_SAM_STACK_NAME=${{ secrets.AWS_SAM_STACK_NAME }}" >> $GITHUB_ENV

      - name: Test API integration
        run: pytest Cloud-Resume-Challenge/backend/tests/integration/test_api_integration.py