name: Terraform Tests

on:
  push:
    branches:
    - backend-chatbot

jobs:
  run-terraform-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: 'read'
      id-token: 'write'

    #Authenticate to GCP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}'

      #Run Terraform tests      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: |
          cd Car_Rental_Chatbot
          terraform init

      - name: Run Terraform Tests
        run: terraform test -test-directory=tests/unit
