name: Terraform Tests

on:
  push:
    branches:
    - backend-chatbot

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: |
          cd Car_Rental_Chatbot
          terraform init

      - name: Run Terraform Tests
        run: terraform test -test-directory=car_rental_chatbot/tests/unit
