name: Terraform Tests

on:
  push:
    branches:
    - backend-chatbot

jobs:

#Authenticate to GCP
  gcp-authentication:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_GITHUB_SERVICE_ACCOUNT }}'


#Run Terraform Tests
  terraform-tests:
    needs: gcp-authentication
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        run: |
          cd Car_Rental_Chatbot
          terraform init

      - name: Run Terraform Tests
        run: terraform test -test-directory=car_rental_chatbot/tests/unit
